DROP SCHEMA IF EXISTS event_lab CASCADE;
CREATE SCHEMA event_lab;
SET search_path TO event_lab, public;

CREATE TABLE events (
    event_id integer PRIMARY KEY,
    event_name text NOT NULL,
    available_seats integer NOT NULL CHECK (available_seats >= 0)
);

CREATE TABLE bookings (
    booking_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id integer NOT NULL REFERENCES events(event_id),
    student_number text NOT NULL,
    seats integer NOT NULL CHECK (seats > 0),
    status text NOT NULL CHECK (status IN ('ACTIVE', 'CANCELLED'))
);

INSERT INTO events (event_id, event_name, available_seats)
VALUES (1, 'Graduation Ceremony', 5),
       (2, 'Tech Talk', 2),
       (3, 'Sports Day', 8);

SELECT * FROM events ORDER BY event_id;

DO $$
DECLARE
    v_seats integer;
BEGIN
    SELECT available_seats INTO v_seats
    FROM events WHERE event_id = 2;

    IF v_seats = 0 THEN
        RAISE NOTICE 'Event full';
    ELSIF v_seats <= 2 THEN
        RAISE NOTICE 'Event nearly full: % seats remaining', v_seats;
    ELSE
        RAISE NOTICE 'Event has plenty of seats: % remaining', v_seats;
    END IF;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    v_day integer := 1;
BEGIN
    WHILE v_day <= 3 LOOP
        RAISE NOTICE 'Booking reminder day %', v_day;
        v_day := v_day + 1;
    END LOOP;

    FOR v_check IN 1..3 LOOP
        RAISE NOTICE 'Entrance check number %', v_check;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE event_lab.book_seats(
    p_event_id integer,
    p_student_number text,
    p_seats integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_booking_id integer;
BEGIN
    IF p_seats <= 0 THEN
        RAISE EXCEPTION 'Number of seats must be positive'
            USING ERRCODE = '22023';
    END IF;

    SELECT available_seats INTO v_available
    FROM event_lab.events
    WHERE event_id = p_event_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Event % does not exist', p_event_id;
        RETURN;
    ELSIF v_available < p_seats THEN
        RAISE NOTICE 'Insufficient seats: only % available', v_available;
        RETURN;
    END IF;

    UPDATE event_lab.events
    SET available_seats = available_seats - p_seats
    WHERE event_id = p_event_id;

    INSERT INTO event_lab.bookings
        (event_id, student_number, seats, status)
    VALUES (p_event_id, p_student_number, p_seats, 'ACTIVE')
    RETURNING booking_id INTO v_booking_id;

    RAISE NOTICE 'Booking % created for student %', v_booking_id, p_student_number;
END;
$$;

CALL event_lab.book_seats(1, 'STU301', 2);
CALL event_lab.book_seats(3, 'STU302', 4);
CALL event_lab.book_seats(2, 'STU303', 5);

SELECT event_id, event_name, available_seats
FROM event_lab.events ORDER BY event_id;

SELECT booking_id, event_id, student_number, seats, status
FROM event_lab.bookings ORDER BY booking_id;


CREATE OR REPLACE PROCEDURE event_lab.cancel_booking(p_booking_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_event_id integer;
    v_seats integer;
BEGIN
    SELECT event_id, seats
    INTO v_event_id, v_seats
    FROM event_lab.bookings
    WHERE booking_id = p_booking_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active booking with ID %', p_booking_id;
        RETURN;
    END IF;

    UPDATE event_lab.bookings
    SET status = 'CANCELLED' WHERE booking_id = p_booking_id;

    UPDATE event_lab.events
    SET available_seats = available_seats + v_seats
    WHERE event_id = v_event_id;

    RAISE NOTICE 'Booking % cancelled; % seats released', p_booking_id, v_seats;
END;
$$;

CALL event_lab.cancel_booking(1);
CALL event_lab.cancel_booking(1);

SELECT * FROM event_lab.events ORDER BY event_id;
SELECT booking_id, status FROM event_lab.bookings ORDER BY booking_id;

CREATE OR REPLACE PROCEDURE event_lab.show_full_or_nearly_full_events()
LANGUAGE plpgsql
AS $$
DECLARE
    v_event record;
    c_low CURSOR FOR
        SELECT event_name, available_seats
        FROM event_lab.events
        WHERE available_seats <= 2
        ORDER BY event_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_event;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Full or nearly full: % (% seats remaining)',
            v_event.event_name, v_event.available_seats;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL event_lab.show_full_or_nearly_full_events();
DO $$
BEGIN
    CALL event_lab.book_seats(3, 'STU304', 0);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;

$$ LANGUAGE plpgsql;
SELECT event_id, event_name, available_seats
FROM event_lab.events ORDER BY event_id;

SELECT booking_id, event_id, student_number, seats, status
FROM event_lab.bookings ORDER BY booking_id;