
DROP SCHEMA IF EXISTS hostel_lab CASCADE;
CREATE SCHEMA hostel_lab;
SET search_path TO hostel_lab, public;

CREATE TABLE hostel_rooms (
    room_id integer PRIMARY KEY,
    room_name text NOT NULL,
    available_beds integer NOT NULL CHECK (available_beds >= 0)
);

CREATE TABLE allocations (
    allocation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id integer NOT NULL REFERENCES hostel_rooms(room_id),
    student_number text NOT NULL,
    status text NOT NULL CHECK (status IN ('ACTIVE', 'CHECKED_OUT'))
);

INSERT INTO hostel_rooms (room_id, room_name, available_beds)
VALUES (1, 'Room A1', 3),
       (2, 'Room B2', 1),
       (3, 'Room C3', 5);

SELECT * FROM hostel_rooms ORDER BY room_id;

DO $$
DECLARE
    v_beds integer;
BEGIN
    SELECT available_beds INTO v_beds
    FROM hostel_rooms WHERE room_id = 2;

    IF v_beds = 0 THEN
        RAISE NOTICE 'Room full';
    ELSIF v_beds = 1 THEN
        RAISE NOTICE 'Room has one space left';
    ELSE
        RAISE NOTICE 'Room has several spaces: % remaining', v_beds;
    END IF;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    v_day integer := 1;
BEGIN
    WHILE v_day <= 3 LOOP
        RAISE NOTICE 'Hostel inspection day %', v_day;
        v_day := v_day + 1;
    END LOOP;

    FOR v_check IN 1..3 LOOP
        RAISE NOTICE 'Room check number %', v_check;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE hostel_lab.allocate_room(
    p_room_id integer,
    p_student_number text
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_allocation_id integer;
BEGIN
    IF p_student_number IS NULL OR trim(p_student_number) = '' THEN
        RAISE EXCEPTION 'Student number must not be blank'
            USING ERRCODE = '22023';
    END IF;

    SELECT available_beds INTO v_available
    FROM hostel_lab.hostel_rooms
    WHERE room_id = p_room_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Room % does not exist', p_room_id;
        RETURN;
    ELSIF v_available < 1 THEN
        RAISE NOTICE 'Room % is full', p_room_id;
        RETURN;
    END IF;

    UPDATE hostel_lab.hostel_rooms
    SET available_beds = available_beds - 1
    WHERE room_id = p_room_id;

    INSERT INTO hostel_lab.allocations
        (room_id, student_number, status)
    VALUES (p_room_id, p_student_number, 'ACTIVE')
    RETURNING allocation_id INTO v_allocation_id;

    RAISE NOTICE 'Allocation % created for student %', v_allocation_id, p_student_number;
END;
$$;

		CALL hostel_lab.allocate_room(1, 'STU201');
		CALL hostel_lab.allocate_room(3, 'STU202');
		CALL hostel_lab.allocate_room(2, 'STU203');
		CALL hostel_lab.allocate_room(2, 'STU204');

SELECT room_id, room_name, available_beds
FROM hostel_lab.hostel_rooms ORDER BY room_id;

SELECT allocation_id, room_id, student_number, status
FROM hostel_lab.allocations ORDER BY allocation_id;


CREATE OR REPLACE PROCEDURE hostel_lab.check_out(p_allocation_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_room_id integer;
BEGIN
    SELECT room_id
    INTO v_room_id
    FROM hostel_lab.allocations
    WHERE allocation_id = p_allocation_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active allocation with ID %', p_allocation_id;
        RETURN;
    END IF;

    UPDATE hostel_lab.allocations
    SET status = 'CHECKED_OUT' WHERE allocation_id = p_allocation_id;

    UPDATE hostel_lab.hostel_rooms
    SET available_beds = available_beds + 1
    WHERE room_id = v_room_id;

    RAISE NOTICE 'Allocation % checked out; 1 bed space released', p_allocation_id;
END;
$$;

CALL hostel_lab.check_out(1);
CALL hostel_lab.check_out(1);

SELECT * FROM hostel_lab.hostel_rooms ORDER BY room_id;
SELECT allocation_id, status FROM hostel_lab.allocations ORDER BY allocation_id;


CREATE OR REPLACE PROCEDURE hostel_lab.show_full_or_nearly_full_rooms()
LANGUAGE plpgsql
AS $$
DECLARE
    v_room record;
    c_low CURSOR FOR
        SELECT room_name, available_beds
        FROM hostel_lab.hostel_rooms
        WHERE available_beds <= 1
        ORDER BY room_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_room;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Full or nearly full: % (% beds remaining)',
            v_room.room_name, v_room.available_beds;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL hostel_lab.show_full_or_nearly_full_rooms();


DO $$
BEGIN
    CALL hostel_lab.allocate_room(3, '');
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;


SELECT room_id, room_name, available_beds
FROM hostel_lab.hostel_rooms ORDER BY room_id;

SELECT allocation_id, room_id, student_number, status
FROM hostel_lab.allocations ORDER BY allocation_id;