DROP SCHEMA IF EXISTS library_lab CASCADE;
--CREATING SCAHEMA
CREATE SCHEMA library_lab;
SET search_path TO library_lab, public;
CREATE TABLE books(
	book_id integer PRIMARY KEY,
	title text NOT NULL,
	available_copies integer NOT NULL CHECK(available_copies >=0)
);

CREATE TABLE book_loans(
	loan_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	book_id integer NOT NULL REFERENCES books(book_id),
	student_number text NOT NULL,
	quantity integer NOT NULL CHECK(quantity > 0),
	status text NOT NULL CHECK(status IN('ACTIVE', 'RETURNED'))
);
INSERT INTO books (book_id, title, available_copies)
VALUES (1, 'Batabase Systems', 4),
	   (2, 'Introduction to Comp.SCience', 6),
	   (3, 'Cyber Security', 9);


	   SELECT * FROM books ORDER BY book_id;

	   DO $$
	   DECLARE
	   v_copies integer;

	   BEGIN 
	   		SELECT available_copies INTO v_copies
		 	FROM books WHERE book_id =2;

			IF v_copies = 0 THEN
				RAISE NOTICE 'BOOK UNAVAILABLE';

			ELSEIF v_copies <=2 THEN
				RAISE NOTICE 'BOOK LOW ON COPIES: % REMAINING', v_copies;

			ELSE 
				RAISE NOTICE 'BOOK SUFFICIENTLY STOCKED: % REMAINING', v_copies;

			END IF;
			
		END;
		$$ LANGUAGE plpgsql;

		DO $$
		DECLARE
			v_reminder integer := 1;
		BEGIN
			WHILE v_reminder <=3 LOOP
				RAISE NOTICE 'OVERDUE REMINDER NUMBER %', v_reminder;
				v_reminder := v_reminder + 1;
		    END LOOP;

			--FOR LOOP;
			
			FOR v_shelf In 1..3 LOOP
				RAISE NOTICE 'Library Shelf number %', v_shelf;

			END LOOP;
		END;
		$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE borrow_book(
	p_book_id integer,
	p_student_number text,
	p_quantity integer
)		
LANGUAGE plpgsql
AS $$
DECLARE
	v_available integer;
	v_loan_id integer;
BEGIN 
	IF p_quantity <=0 THEN 
	RAISE EXCEPTION 'QUANTITY MUST BE POSITIVE'
		USING ERRCODE = '22023';

	END IF;

	--IF NOT FOUND THEN 
	SELECT available_copies INTO v_available
	FROM books 
	WHERE book_id = p_book_id
	FOR UPDATE;

	IF NOT FOUND THEN
		RAISE NOTICE 'BOOK % DOES NOT EXIST', p_book_id;
		RETURN;

	ELSEIF v_available < p_quantity THEN
		RAISE NOTICE ' INSUFFICIENT COPIES: ONLY % AVAILABLE', p_available;
		RETURN;
	END IF;

	UPDATE books
	SET available_copies = available_copies - p_quantity
	WHERE book_id = p_book_id;

	INSERT INTO book_loans
		(book_id, student_number, quantity, status)
	Values (p_book_id, p_student_number, p_quantity, 'ACTIVE')
	RETURNING loan_id INTO v_loan_id;

	RAISE NOTICE 'LOAN % CREATED FOR STUDENT %', v_loan_id, p_student_number;

END;
$$;

CALL borrow_book(1, 'STU101', 2);
CALL borrow_book(2, 'STU102', 4);
CALL borrow_book(3, 'STU103', 8);

SELECT book_id, title, available_copies
FROM books ORDER BY book_id;

SELECT book_id, title, available_copies
FROM books ORDER BY book_id;

SELECT loan_id, book_id, student_number, quantity, status
FROM book_loans ORDER BY loan_id;

CREATE OR REPLACE PROCEDURE return_book(p_loan_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_book_id integer;
    v_quantity integer;
BEGIN
    SELECT book_id, quantity
    INTO v_book_id, v_quantity
    FROM book_loans
    WHERE loan_id = p_loan_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active loan with ID %', p_loan_id;
        RETURN;
    END IF;

    UPDATE book_loans
    SET status = 'RETURNED' WHERE loan_id = p_loan_id;

    UPDATE books
    SET available_copies = available_copies + v_quantity
    WHERE book_id = v_book_id;

    RAISE NOTICE 'Loan % returned; % copies restored', p_loan_id, v_quantity;
END;
$$;

CALL return_book(1);
CALL return_book(1);

SELECT * FROM books ORDER BY book_id;
SELECT loan_id, status FROM book_loans ORDER BY loan_id;

CREATE OR REPLACE PROCEDURE show_low_stock_books()
LANGUAGE plpgsql
AS $$
DECLARE
    v_book record;
    c_low CURSOR FOR
        SELECT title, available_copies
        FROM books
        WHERE available_copies <= 2
        ORDER BY book_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_book;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Low stock: % (% remaining)', v_book.title, v_book.available_copies;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL show_low_stock_books();

DO $$
BEGIN
    CALL borrow_book(3, 'STU104', 0);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

SELECT book_id, title, available_copies
FROM books ORDER BY book_id;

SELECT loan_id, book_id, student_number, quantity, status
FROM book_loans ORDER BY loan_id;