DROP SCHEMA IF EXISTS labres_lab CASCADE;
CREATE SCHEMA labres_lab;
SET search_path TO labres_lab, public;

CREATE TABLE lab_sessions (
    session_id integer PRIMARY KEY,
    session_name text NOT NULL,
    available_workstations integer NOT NULL CHECK (available_workstations >= 0)
);

CREATE TABLE reservations (
    reservation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES lab_sessions(session_id),
    lecturer text NOT NULL,
    workstations integer NOT NULL CHECK (workstations > 0),
    status text NOT NULL CHECK (status IN ('ACTIVE', 'CANCELLED'))
);

INSERT INTO lab_sessions (session_id, session_name, available_workstations)
VALUES (1, 'Morning Practical', 6),
       (2, 'Afternoon Practical', 2),
       (3, 'Evening Practical', 10);

SELECT * FROM lab_sessions ORDER BY session_id;

DO $$
DECLARE
    v_available integer;
BEGIN
    SELECT available_workstations INTO v_available
    FROM lab_sessions WHERE session_id = 2;

    IF v_available = 0 THEN
        RAISE NOTICE 'Session full';
    ELSIF v_available <= 2 THEN
        RAISE NOTICE 'Session nearly full: % workstations remaining', v_available;
    ELSE
        RAISE NOTICE 'Session has enough workstations: % remaining', v_available;
    END IF;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    v_reminder integer := 1;
BEGIN
    WHILE v_reminder <= 3 LOOP
        RAISE NOTICE 'Session preparation reminder %', v_reminder;
        v_reminder := v_reminder + 1;
    END LOOP;

    FOR v_check IN 1..3 LOOP
        RAISE NOTICE 'Workstation check number %', v_check;
    END LOOP;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE PROCEDURE labres_lab.reserve_workstations(
    p_session_id integer,
    p_lecturer text,
    p_workstations integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_reservation_id integer;
BEGIN
    IF p_workstations <= 0 THEN
        RAISE EXCEPTION 'Number of workstations must be positive'
            USING ERRCODE = '22023';
    END IF;

    SELECT available_workstations INTO v_available
    FROM labres_lab.lab_sessions
    WHERE session_id = p_session_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Session % does not exist', p_session_id;
        RETURN;
    ELSIF v_available < p_workstations THEN
        RAISE NOTICE 'Insufficient workstations: only % available', v_available;
        RETURN;
    END IF;

    UPDATE labres_lab.lab_sessions
    SET available_workstations = available_workstations - p_workstations
    WHERE session_id = p_session_id;

    INSERT INTO labres_lab.reservations
        (session_id, lecturer, workstations, status)
    VALUES (p_session_id, p_lecturer, p_workstations, 'ACTIVE')
    RETURNING reservation_id INTO v_reservation_id;

    RAISE NOTICE 'Reservation % created for lecturer %', v_reservation_id, p_lecturer;
END;
$$;


CALL labres_lab.reserve_workstations(1, 'Dr. Banda', 4);
CALL labres_lab.reserve_workstations(3, 'Dr. Phiri', 5);
CALL labres_lab.reserve_workstations(2, 'Dr. Mwale', 10);

SELECT session_id, session_name, available_workstations
FROM labres_lab.lab_sessions ORDER BY session_id;

SELECT reservation_id, session_id, lecturer, workstations, status
FROM labres_lab.reservations ORDER BY reservation_id;

CREATE OR REPLACE PROCEDURE labres_lab.cancel_reservation(p_reservation_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_session_id integer;
    v_workstations integer;
BEGIN
    SELECT session_id, workstations
    INTO v_session_id, v_workstations
    FROM labres_lab.reservations
    WHERE reservation_id = p_reservation_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active reservation with ID %', p_reservation_id;
        RETURN;
    END IF;

    UPDATE labres_lab.reservations
    SET status = 'CANCELLED' WHERE reservation_id = p_reservation_id;

    UPDATE labres_lab.lab_sessions
    SET available_workstations = available_workstations + v_workstations
    WHERE session_id = v_session_id;

    RAISE NOTICE 'Reservation % cancelled; % workstations released', p_reservation_id, v_workstations;
END;
$$;

CALL labres_lab.cancel_reservation(1);
CALL labres_lab.cancel_reservation(1);

SELECT * FROM labres_lab.lab_sessions ORDER BY session_id;
SELECT reservation_id, status FROM labres_lab.reservations ORDER BY reservation_id;

CREATE OR REPLACE PROCEDURE labres_lab.show_low_availability_sessions()
LANGUAGE plpgsql
AS $$
DECLARE
    v_session record;
    c_low CURSOR FOR
        SELECT session_name, available_workstations
        FROM labres_lab.lab_sessions
        WHERE available_workstations <= 2
        ORDER BY session_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_session;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Low availability: % (% workstations remaining)',
            v_session.session_name, v_session.available_workstations;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL labres_lab.show_low_availability_sessions();

DO $$
BEGIN
    CALL labres_lab.reserve_workstations(3, 'Dr. Zulu', 0);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;


SELECT session_id, session_name, available_workstations
FROM labres_lab.lab_sessions ORDER BY session_id;

SELECT reservation_id, session_id, lecturer, workstations, status
FROM labres_lab.reservations ORDER BY reservation_id;